version: '3.9'
services:
  web-action-sso:
    image: nginx:latest
    ports:
      - "8228:80"
    volumes:
      - ./sources/action-sso/:/action-sso
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - database-action-sso
      - php-action-sso
  
  php-action-sso:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php-action-sso
    working_dir: /action-sso/
    restart: always
    volumes:
      - ./sources/action-sso/:/action-sso
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro
    expose:
      - "9000"
    command: >
        bash -c "true
        && composer install
        && docker-php-entrypoint php-fpm
        && php bin/console doctrine:migrations:migrate"
        
  database-action-sso:
    image: mariadb:latest
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8220:80
    environment:
      - PMA_ARBITRARY=1
